/*
 * This file was automatically generated by EvoSuite
 * Mon May 15 08:45:27 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EvenOrOdd_ESTest extends EvenOrOdd_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = EvenOrOdd.check((-2657));
      assertEquals("odd", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = EvenOrOdd.check(1);
      assertEquals("odd", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = EvenOrOdd.check(3872);
      assertEquals("even", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EvenOrOdd evenOrOdd0 = new EvenOrOdd();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[9];
      EvenOrOdd.main(stringArray0);
      assertEquals(9, stringArray0.length);
  }
}
