/*
 * This file was automatically generated by EvoSuite
 * Mon May 15 06:38:00 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Calculator_ESTest extends Calculator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      SystemInUtil.addInputLine("1");
      SystemInUtil.addInputLine("-");
      String[] stringArray0 = new String[11];
      Calculator.main(stringArray0);
      assertEquals(11, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[] stringArray0 = new String[11];
      // Undeclared exception!
      try { 
        Calculator.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SystemInUtil.addInputLine("5 YLx78#bMc");
      // Undeclared exception!
      try { 
        Calculator.main((String[]) null);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      SystemInUtil.addInputLine("1");
      SystemInUtil.addInputLine("/");
      Calculator.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      SystemInUtil.addInputLine("5 YL1YfO]x38#PMJ");
      String[] stringArray0 = new String[16];
      Calculator.main(stringArray0);
      assertEquals(16, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      SystemInUtil.addInputLine("0");
      SystemInUtil.addInputLine("/");
      String[] stringArray0 = new String[16];
      Calculator.main(stringArray0);
      assertEquals(16, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SystemInUtil.addInputLine("21");
      SystemInUtil.addInputLine("21");
      SystemInUtil.addInputLine(".");
      Calculator.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      SystemInUtil.addInputLine("0");
      SystemInUtil.addInputLine("-");
      String[] stringArray0 = new String[11];
      Calculator.main(stringArray0);
      assertEquals(11, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine(",");
      String[] stringArray0 = new String[9];
      Calculator.main(stringArray0);
      assertEquals(9, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      SystemInUtil.addInputLine("1");
      SystemInUtil.addInputLine("+");
      String[] stringArray0 = new String[11];
      Calculator.main(stringArray0);
      assertEquals(11, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SystemInUtil.addInputLine("21");
      SystemInUtil.addInputLine("21");
      SystemInUtil.addInputLine("*");
      String[] stringArray0 = new String[12];
      Calculator.main(stringArray0);
      assertEquals(12, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Calculator calculator0 = new Calculator();
  }
}
